language: java
jdk:
  - openjdk14
services:
  - mysql
script: "./gradlew clean build"
sudo: required
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e 'CREATE DATABASE LAS2PEERMON;'
  - mysql -u root LAS2PEERMON < bin/db.sql
  - mysql -u root LAS2PEERMON < etc/migrations/migrate-v1-mysql.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
